USE [master]
GO
/****** Object:  Database [BDAPETZ]    Script Date: 06/12/2022 20:41:01 ******/
CREATE DATABASE [BDAPETZ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDAPETZ_Data', FILENAME = N'c:\dzsqls\BDAPETZ.mdf' , SIZE = 8192KB , MAXSIZE = 30720KB , FILEGROWTH = 22528KB )
 LOG ON 
( NAME = N'BDAPETZ_Logs', FILENAME = N'c:\dzsqls\BDAPETZ.ldf' , SIZE = 8192KB , MAXSIZE = 30720KB , FILEGROWTH = 22528KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDAPETZ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDAPETZ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDAPETZ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDAPETZ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDAPETZ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDAPETZ] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDAPETZ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BDAPETZ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDAPETZ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDAPETZ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDAPETZ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDAPETZ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDAPETZ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDAPETZ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDAPETZ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDAPETZ] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BDAPETZ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDAPETZ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDAPETZ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDAPETZ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDAPETZ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDAPETZ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDAPETZ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDAPETZ] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BDAPETZ] SET  MULTI_USER 
GO
ALTER DATABASE [BDAPETZ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDAPETZ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDAPETZ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDAPETZ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BDAPETZ] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BDAPETZ] SET QUERY_STORE = OFF
GO
USE [BDAPETZ]
GO
/****** Object:  User [Ametistapetz_SQLLogin_1]    Script Date: 06/12/2022 20:41:20 ******/
CREATE USER [Ametistapetz_SQLLogin_1] FOR LOGIN [Ametistapetz_SQLLogin_1] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [Ametistapetz_SQLLogin_1]
GO
/****** Object:  Schema [Ametistapetz_SQLLogin_1]    Script Date: 06/12/2022 20:41:22 ******/
CREATE SCHEMA [Ametistapetz_SQLLogin_1]
GO
/****** Object:  UserDefinedFunction [dbo].[Password_Check]    Script Date: 06/12/2022 20:41:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[Password_Check]
	(
		@v1 varchar(500)
	)
	RETURNS  varchar(7)
	AS
	BEGIN
		DECLARE @result varchar(7)
 
 
	Select
		@result  =( CASE when [PasswordString] =  HASHBYTES('SHA2_512', @v1) THEN 'Valid'
			ELSE 'Invalid'
		END )
		from Login
		where  [PasswordString] =  HASHBYTES('SHA2_512', @v1) 
 
	RETURN @result
	END
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 06/12/2022 20:41:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Animal]    Script Date: 06/12/2022 20:41:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Animal](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](20) NOT NULL,
	[IdEspecie] [int] NOT NULL,
	[IdRaca] [int] NOT NULL,
	[IdSexo] [int] NOT NULL,
	[DtNascimento] [smalldatetime] NOT NULL,
	[Pelagem] [varchar](15) NULL,
	[IdSituacao] [int] NOT NULL,
	[Peso] [float] NOT NULL,
	[DataAdicao] [datetime] NULL,
	[IdLogin] [int] NULL,
 CONSTRAINT [PK_Animal] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Carteira]    Script Date: 06/12/2022 20:41:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carteira](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AnimalIdAnimal] [int] NULL,
	[DataAdicao] [datetime] NULL,
 CONSTRAINT [PK_Carteira] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Desaparecido]    Script Date: 06/12/2022 20:41:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Desaparecido](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DtDesaparecimento] [datetime] NULL,
	[Lugar] [varchar](25) NOT NULL,
	[Telefone] [varchar](13) NOT NULL,
	[IdAnimal] [int] NULL,
	[Dono] [varchar](45) NULL,
 CONSTRAINT [PK_Desaparecido] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DesaparecidoSemRegistro]    Script Date: 06/12/2022 20:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DesaparecidoSemRegistro](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](45) NOT NULL,
	[Especie] [varchar](45) NOT NULL,
	[Raca] [varchar](45) NOT NULL,
	[DtDesaparecimento] [date] NOT NULL,
	[Lugar] [varchar](45) NOT NULL,
	[Telefone] [varchar](45) NOT NULL,
	[Foto] [varchar](max) NOT NULL,
	[Dono] [varchar](45) NOT NULL,
 CONSTRAINT [PK_DesaparecidoNaoRegistrado] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Especie]    Script Date: 06/12/2022 20:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Especie](
	[idEspecie] [int] NOT NULL,
	[EspecieAnimal] [varchar](15) NOT NULL,
	[GrupoAnimal] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Especie] PRIMARY KEY CLUSTERED 
(
	[idEspecie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 06/12/2022 20:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PasswordHash] [varbinary](8000) NOT NULL,
	[username] [varchar](4000) NULL,
	[PasswordString] [varchar](4000) NULL,
	[PasswordSalt] [varbinary](8000) NULL,
 CONSTRAINT [PK_LOGIN] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Perfil]    Script Date: 06/12/2022 20:41:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Perfil](
	[idPerfil] [int] NOT NULL,
	[Descricao] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Perfil] PRIMARY KEY CLUSTERED 
(
	[idPerfil] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Racas]    Script Date: 06/12/2022 20:41:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Racas](
	[idRaca] [int] NOT NULL,
	[idEspecie] [int] NOT NULL,
	[dsRaca] [varchar](30) NOT NULL,
	[ptRaca] [varchar](10) NOT NULL,
	[crRaca] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Racas] PRIMARY KEY CLUSTERED 
(
	[idRaca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RGA]    Script Date: 06/12/2022 20:41:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RGA](
	[IdRGA] [int] IDENTITY(1,1) NOT NULL,
	[IdAnimal] [int] NOT NULL,
	[Chip] [int] NULL,
	[Rga] [int] NULL,
	[Assinatura] [varchar](max) NULL,
	[Pata] [varchar](max) NULL,
	[Foto] [varchar](max) NULL,
	[DataAdicao] [datetime] NULL,
 CONSTRAINT [PK_RGA] PRIMARY KEY CLUSTERED 
(
	[IdRGA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sexos]    Script Date: 06/12/2022 20:41:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sexos](
	[idSexo] [int] NOT NULL,
	[dsSexo] [char](5) NOT NULL,
 CONSTRAINT [PK_Sexos] PRIMARY KEY CLUSTERED 
(
	[idSexo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Situacao]    Script Date: 06/12/2022 20:41:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Situacao](
	[idSituacao] [int] NOT NULL,
	[dsSituacao] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Situacao] PRIMARY KEY CLUSTERED 
(
	[idSituacao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tutor]    Script Date: 06/12/2022 20:41:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tutor](
	[idTutor] [int] NOT NULL,
	[cpTutor] [char](11) NOT NULL,
	[nmTutor] [varchar](40) NOT NULL,
	[enTutor] [varchar](40) NOT NULL,
	[neTutor] [varchar](10) NOT NULL,
	[cmTutor] [varchar](15) NOT NULL,
	[baTutor] [varchar](20) NOT NULL,
	[mnTutor] [varchar](25) NOT NULL,
	[ufTutor] [char](2) NOT NULL,
	[Email] [varchar](1) NOT NULL,
	[CRM] [char](5) NOT NULL,
	[idPerfil] [int] NOT NULL,
 CONSTRAINT [PK_Tutor] PRIMARY KEY CLUSTERED 
(
	[idTutor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tutor_Animal]    Script Date: 06/12/2022 20:41:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tutor_Animal](
	[idTutor] [int] NOT NULL,
	[idAnimal] [int] NOT NULL,
	[dtInicio] [smalldatetime] NOT NULL,
 CONSTRAINT [PK_Tutor_Animal] PRIMARY KEY CLUSTERED 
(
	[idTutor] ASC,
	[idAnimal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vacina]    Script Date: 06/12/2022 20:41:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vacina](
	[IdVacina] [int] IDENTITY(1,1) NOT NULL,
	[DataVacina] [datetime] NOT NULL,
	[ProximaVacina] [datetime] NULL,
	[Medicamento] [varchar](30) NULL,
	[CarteiraId] [int] NOT NULL,
 CONSTRAINT [PK_Vacina] PRIMARY KEY CLUSTERED 
(
	[IdVacina] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_01] FOREIGN KEY([IdEspecie])
REFERENCES [dbo].[Especie] ([idEspecie])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_01]
GO
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_02] FOREIGN KEY([IdSexo])
REFERENCES [dbo].[Sexos] ([idSexo])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_02]
GO
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_03] FOREIGN KEY([IdSituacao])
REFERENCES [dbo].[Situacao] ([idSituacao])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_03]
GO
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_04] FOREIGN KEY([IdRaca])
REFERENCES [dbo].[Racas] ([idRaca])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_04]
GO
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_ANIMAL_10] FOREIGN KEY([IdLogin])
REFERENCES [dbo].[Login] ([Id])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_ANIMAL_10]
GO
ALTER TABLE [dbo].[Carteira]  WITH CHECK ADD  CONSTRAINT [FK_Carteira_01] FOREIGN KEY([AnimalIdAnimal])
REFERENCES [dbo].[Animal] ([Id])
GO
ALTER TABLE [dbo].[Carteira] CHECK CONSTRAINT [FK_Carteira_01]
GO
ALTER TABLE [dbo].[Desaparecido]  WITH CHECK ADD  CONSTRAINT [FK_Desaparecido_01] FOREIGN KEY([IdAnimal])
REFERENCES [dbo].[Animal] ([Id])
GO
ALTER TABLE [dbo].[Desaparecido] CHECK CONSTRAINT [FK_Desaparecido_01]
GO
ALTER TABLE [dbo].[RGA]  WITH CHECK ADD  CONSTRAINT [FK_RGA_02] FOREIGN KEY([IdAnimal])
REFERENCES [dbo].[Animal] ([Id])
GO
ALTER TABLE [dbo].[RGA] CHECK CONSTRAINT [FK_RGA_02]
GO
ALTER TABLE [dbo].[Tutor]  WITH CHECK ADD  CONSTRAINT [FK_Tutor_01] FOREIGN KEY([idPerfil])
REFERENCES [dbo].[Perfil] ([idPerfil])
GO
ALTER TABLE [dbo].[Tutor] CHECK CONSTRAINT [FK_Tutor_01]
GO
ALTER TABLE [dbo].[Tutor_Animal]  WITH CHECK ADD  CONSTRAINT [FK_Tutor_Animal_01] FOREIGN KEY([idTutor])
REFERENCES [dbo].[Tutor] ([idTutor])
GO
ALTER TABLE [dbo].[Tutor_Animal] CHECK CONSTRAINT [FK_Tutor_Animal_01]
GO
ALTER TABLE [dbo].[Vacina]  WITH CHECK ADD  CONSTRAINT [FK_Vacina_01] FOREIGN KEY([CarteiraId])
REFERENCES [dbo].[Carteira] ([Id])
GO
ALTER TABLE [dbo].[Vacina] CHECK CONSTRAINT [FK_Vacina_01]
GO
/****** Object:  StoredProcedure [dbo].[INSERT_CURRENT_DATE]    Script Date: 06/12/2022 20:41:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERT_CURRENT_DATE] 
AS
	DECLARE @dataAdicao DATETIME
	SELECT @dataAdicao = DataAdicao FROM RGA
	IF @dataAdicao = NULL
	BEGIN
		SELECT @dataAdicao = CURRENT_TIMESTAMP
		UPDATE RGA SET DataAdicao = @dataAdicao WHERE DataAdicao = NULL
	END
GO
/****** Object:  StoredProcedure [dbo].[INSERT_CURRENT_DATE_02]    Script Date: 06/12/2022 20:41:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERT_CURRENT_DATE_02] @dataAdicao DATETIME
AS
	IF EXISTS(SELECT DataAdicao FROM Animal WHERE DataAdicao is NULL)
	BEGIN
		SELECT @dataAdicao = CURRENT_TIMESTAMP
		UPDATE Animal SET DataAdicao = @dataAdicao WHERE DataAdicao IS NULL
	END
GO
/****** Object:  StoredProcedure [dbo].[INSERT_CURRENT_DATE_03]    Script Date: 06/12/2022 20:41:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERT_CURRENT_DATE_03]
AS
	DECLARE @dataAdicao DATETIME
	SELECT @dataAdicao = DataAdicao FROM Carteira
	IF @dataAdicao = NULL
	BEGIN
		SELECT @dataAdicao = CURRENT_TIMESTAMP
		UPDATE Carteira SET DataAdicao = @dataAdicao WHERE DataAdicao IS NULL
	END
GO
USE [master]
GO
ALTER DATABASE [BDAPETZ] SET  READ_WRITE 
GO
