// <auto-generated />
using System;
using CarteiraVacina_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace carteiravacina.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("carteiravacina.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EspecieIdEspecie")
                        .HasColumnType("int");

                    b.Property<int>("IdRGA")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RacasIdEspecie")
                        .HasColumnType("int");

                    b.Property<int?>("RacasIdRaca")
                        .HasColumnType("int");

                    b.Property<int?>("SexosIdSexo")
                        .HasColumnType("int");

                    b.Property<string>("SituacaoDescricaoSituacao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SituacaoIdSituacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<float>("peso")
                        .HasColumnType("real");

                    b.HasKey("IdAnimal");

                    b.HasIndex("EspecieIdEspecie");

                    b.HasIndex("SexosIdSexo");

                    b.HasIndex("RacasIdRaca", "RacasIdEspecie");

                    b.HasIndex("SituacaoIdSituacao", "SituacaoDescricaoSituacao");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("carteiravacina.Models.CarteiraVacina", b =>
                {
                    b.Property<int>("IdCarteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnimalIdAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Medicamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProxVacina")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoVacina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataVacina")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCarteira");

                    b.HasIndex("AnimalIdAnimal");

                    b.ToTable("CarteiraVacina");
                });

            modelBuilder.Entity("carteiravacina.Models.Especie", b =>
                {
                    b.Property<int>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EspecieAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupoAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEspecie");

                    b.ToTable("Especie");

                    b.HasData(
                        new
                        {
                            IdEspecie = 1,
                            EspecieAnimal = "Cachorro",
                            GrupoAnimal = "Canina"
                        },
                        new
                        {
                            IdEspecie = 2,
                            EspecieAnimal = "Gato",
                            GrupoAnimal = "Felinos"
                        });
                });

            modelBuilder.Entity("carteiravacina.Models.Login", b =>
                {
                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PasswordHash");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("carteiravacina.Models.Perfil", b =>
                {
                    b.Property<int>("IdCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCodigo");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("carteiravacina.Models.Racas", b =>
                {
                    b.Property<int>("IdRaca")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoRaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorteRaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("crRaca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRaca", "IdEspecie");

                    b.ToTable("Racas");

                    b.HasData(
                        new
                        {
                            IdRaca = 1,
                            IdEspecie = 1,
                            DescricaoRaca = "Akita",
                            PorteRaca = "Alto",
                            crRaca = "Leal, amigo e brincalhão"
                        },
                        new
                        {
                            IdRaca = 2,
                            IdEspecie = 1,
                            DescricaoRaca = "Basset hound",
                            PorteRaca = "Alto",
                            crRaca = "Paciente, teimoso e charmoso"
                        },
                        new
                        {
                            IdRaca = 3,
                            IdEspecie = 1,
                            DescricaoRaca = "Beagle",
                            PorteRaca = "Médio",
                            crRaca = "Alegre, companheiro e aventureiro"
                        },
                        new
                        {
                            IdRaca = 4,
                            IdEspecie = 1,
                            DescricaoRaca = "Bichon frisé",
                            PorteRaca = "Médio",
                            crRaca = "Brincalhão, curioso e afetivo"
                        },
                        new
                        {
                            IdRaca = 5,
                            IdEspecie = 1,
                            DescricaoRaca = "Boiadeiro australiano",
                            PorteRaca = "Médio",
                            crRaca = "Alerta, curioso e leal"
                        },
                        new
                        {
                            IdRaca = 6,
                            IdEspecie = 1,
                            DescricaoRaca = "Border collie",
                            PorteRaca = "Alto",
                            crRaca = "Inteligente, leal e cheio de energia"
                        },
                        new
                        {
                            IdRaca = 7,
                            IdEspecie = 1,
                            DescricaoRaca = "Boston terrier",
                            PorteRaca = "Médio",
                            crRaca = "Amigável, inteligente e vivaz"
                        },
                        new
                        {
                            IdRaca = 8,
                            IdEspecie = 1,
                            DescricaoRaca = "Boxer",
                            PorteRaca = "Alto",
                            crRaca = "Leal, afetuoso e brincalhão"
                        },
                        new
                        {
                            IdRaca = 9,
                            IdEspecie = 1,
                            DescricaoRaca = "Buldogue francês",
                            PorteRaca = "Alto",
                            crRaca = "Carinhoso, leal e brincalhão"
                        },
                        new
                        {
                            IdRaca = 10,
                            IdEspecie = 1,
                            DescricaoRaca = "Buldogue inglês",
                            PorteRaca = "Alto",
                            crRaca = "Calmo, divertido e dócil"
                        },
                        new
                        {
                            IdRaca = 11,
                            IdEspecie = 1,
                            DescricaoRaca = "Bull terrier",
                            PorteRaca = "Médio",
                            crRaca = "Travesso, brincalhão e leal"
                        },
                        new
                        {
                            IdRaca = 12,
                            IdEspecie = 1,
                            DescricaoRaca = "Cane corso",
                            PorteRaca = "Baixo",
                            crRaca = "Protetor, leal e inteligente"
                        },
                        new
                        {
                            IdRaca = 13,
                            IdEspecie = 1,
                            DescricaoRaca = "Cavalier king charles spaniel",
                            PorteRaca = "Alto",
                            crRaca = "Companheiro, alegre e afetuoso"
                        },
                        new
                        {
                            IdRaca = 14,
                            IdEspecie = 1,
                            DescricaoRaca = "Chihuahua",
                            PorteRaca = "Médio",
                            crRaca = "Charmoso, animado e atrevido"
                        },
                        new
                        {
                            IdRaca = 15,
                            IdEspecie = 1,
                            DescricaoRaca = "Chow chow",
                            PorteRaca = "Alto",
                            crRaca = "Calmo, leal e orgulhoso"
                        },
                        new
                        {
                            IdRaca = 16,
                            IdEspecie = 1,
                            DescricaoRaca = "Cocker spaniel inglês",
                            PorteRaca = "Alto",
                            crRaca = "Alegre, carinhoso e cheio de vida"
                        },
                        new
                        {
                            IdRaca = 17,
                            IdEspecie = 1,
                            DescricaoRaca = "Dachshund",
                            PorteRaca = "Médio",
                            crRaca = "Corajoso, animado e inteligente"
                        },
                        new
                        {
                            IdRaca = 18,
                            IdEspecie = 1,
                            DescricaoRaca = "Dálmata",
                            PorteRaca = "Médio",
                            crRaca = "Atlético, protetor e amável"
                        },
                        new
                        {
                            IdRaca = 19,
                            IdEspecie = 1,
                            DescricaoRaca = "Doberman",
                            PorteRaca = "Médio",
                            crRaca = "Inteligente, leal e protetor"
                        },
                        new
                        {
                            IdRaca = 20,
                            IdEspecie = 1,
                            DescricaoRaca = "Dogo argentino",
                            PorteRaca = "Médio",
                            crRaca = "Leal, confiável e corajoso"
                        },
                        new
                        {
                            IdRaca = 21,
                            IdEspecie = 1,
                            DescricaoRaca = "Dogue alemão",
                            PorteRaca = "Alto",
                            crRaca = "Amigável, paciente e dócil"
                        },
                        new
                        {
                            IdRaca = 22,
                            IdEspecie = 1,
                            DescricaoRaca = "Fila brasileiro",
                            PorteRaca = "Baixo",
                            crRaca = "Companheiro, corajoso e amoroso"
                        },
                        new
                        {
                            IdRaca = 23,
                            IdEspecie = 1,
                            DescricaoRaca = "Golden retriever",
                            PorteRaca = "Alto",
                            crRaca = "Inteligente, brincalhão e leal"
                        },
                        new
                        {
                            IdRaca = 24,
                            IdEspecie = 1,
                            DescricaoRaca = "Husky siberiano",
                            PorteRaca = "Médio",
                            crRaca = "Amigável, trabalhador e extrovertido"
                        },
                        new
                        {
                            IdRaca = 25,
                            IdEspecie = 1,
                            DescricaoRaca = "Jack russell terrier",
                            PorteRaca = "Médio",
                            crRaca = "Amigável, atlético e alerta"
                        },
                        new
                        {
                            IdRaca = 26,
                            IdEspecie = 1,
                            DescricaoRaca = "Labrador retriever",
                            PorteRaca = "Médio",
                            crRaca = "Inteligente, carinhoso e brincalhão"
                        },
                        new
                        {
                            IdRaca = 27,
                            IdEspecie = 1,
                            DescricaoRaca = "Lhasa apso",
                            PorteRaca = "Médio",
                            crRaca = "Esperto, confiante e independente"
                        },
                        new
                        {
                            IdRaca = 28,
                            IdEspecie = 1,
                            DescricaoRaca = "Lulu da pomerânia",
                            PorteRaca = "Médio",
                            crRaca = "Animado, inteligente e cheio de personalidade"
                        },
                        new
                        {
                            IdRaca = 29,
                            IdEspecie = 1,
                            DescricaoRaca = "Maltês",
                            PorteRaca = "Médio",
                            crRaca = "Gentil, brincalhão e afetuoso"
                        },
                        new
                        {
                            IdRaca = 30,
                            IdEspecie = 1,
                            DescricaoRaca = "Mastiff inglês",
                            PorteRaca = "Alto",
                            crRaca = "Calmo, amável e leal"
                        },
                        new
                        {
                            IdRaca = 31,
                            IdEspecie = 1,
                            DescricaoRaca = "Mastim tibetano",
                            PorteRaca = "Alto",
                            crRaca = "Independente, reservado e inteligente"
                        },
                        new
                        {
                            IdRaca = 32,
                            IdEspecie = 1,
                            DescricaoRaca = "Pastor alemão",
                            PorteRaca = "Alto",
                            crRaca = "Confiante, corajoso e inteligente"
                        },
                        new
                        {
                            IdRaca = 33,
                            IdEspecie = 1,
                            DescricaoRaca = "Pastor australiano",
                            PorteRaca = "Alto",
                            crRaca = "Esperto, trabalhador e exuberante"
                        },
                        new
                        {
                            IdRaca = 34,
                            IdEspecie = 1,
                            DescricaoRaca = "Pastor de Shetland",
                            PorteRaca = "Médio",
                            crRaca = "Brincalhão, energético e esperto"
                        },
                        new
                        {
                            IdRaca = 35,
                            IdEspecie = 1,
                            DescricaoRaca = "Pequinês",
                            PorteRaca = "Médio",
                            crRaca = "Afetuoso, leal e elegante"
                        },
                        new
                        {
                            IdRaca = 36,
                            IdEspecie = 1,
                            DescricaoRaca = "Pinscher",
                            PorteRaca = "Médio",
                            crRaca = "Brincalhão, carinhoso e protetor"
                        },
                        new
                        {
                            IdRaca = 37,
                            IdEspecie = 1,
                            DescricaoRaca = "Pit bull",
                            PorteRaca = "Médio",
                            crRaca = "Inteligente, forte e leal"
                        },
                        new
                        {
                            IdRaca = 38,
                            IdEspecie = 1,
                            DescricaoRaca = "Poodle",
                            PorteRaca = "Médio",
                            crRaca = "Orgulhoso, ativo e inteligente"
                        },
                        new
                        {
                            IdRaca = 39,
                            IdEspecie = 1,
                            DescricaoRaca = "Pug",
                            PorteRaca = "Alto",
                            crRaca = "Amoroso, temperamental e companheiro"
                        },
                        new
                        {
                            IdRaca = 40,
                            IdEspecie = 1,
                            DescricaoRaca = "Rottweiler",
                            PorteRaca = "Alto",
                            crRaca = "Protetor, leal e inteligente"
                        },
                        new
                        {
                            IdRaca = 41,
                            IdEspecie = 1,
                            DescricaoRaca = "Schnauzer",
                            PorteRaca = "Médio",
                            crRaca = "Dócil, leal e companheiro"
                        },
                        new
                        {
                            IdRaca = 42,
                            IdEspecie = 1,
                            DescricaoRaca = "Shar-pei",
                            PorteRaca = "Alto",
                            crRaca = "Amoroso, companheiro e brincalhão"
                        },
                        new
                        {
                            IdRaca = 43,
                            IdEspecie = 1,
                            DescricaoRaca = "Shiba",
                            PorteRaca = "Baixo",
                            crRaca = "Independente, leal e alerta"
                        },
                        new
                        {
                            IdRaca = 44,
                            IdEspecie = 1,
                            DescricaoRaca = "Shih tzu",
                            PorteRaca = "Médio",
                            crRaca = "Carinhoso, brincalhão e encantador"
                        },
                        new
                        {
                            IdRaca = 45,
                            IdEspecie = 1,
                            DescricaoRaca = "Staffordshire bull terrier",
                            PorteRaca = "Médio",
                            crRaca = "Inteligente, corajoso e determinado"
                        },
                        new
                        {
                            IdRaca = 46,
                            IdEspecie = 1,
                            DescricaoRaca = "Weimaraner",
                            PorteRaca = "Baixo",
                            crRaca = "Amigável, corajoso e independente"
                        },
                        new
                        {
                            IdRaca = 47,
                            IdEspecie = 1,
                            DescricaoRaca = "Yorkshire",
                            PorteRaca = "Médio",
                            crRaca = "Destemido, carinhoso e cheio de energia"
                        },
                        new
                        {
                            IdRaca = 48,
                            IdEspecie = 2,
                            DescricaoRaca = "Ojos Azules",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 49,
                            IdEspecie = 2,
                            DescricaoRaca = "Oregon Rex",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 50,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo curto americano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 51,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo curto brasileiro",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 52,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo curto Europeu",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 53,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo curto inglês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 54,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo longo Inglês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 55,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo curto Oriental",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 56,
                            IdEspecie = 2,
                            DescricaoRaca = "Pelo longo Oriental",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 57,
                            IdEspecie = 2,
                            DescricaoRaca = "Persa",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 58,
                            IdEspecie = 2,
                            DescricaoRaca = "Peterbald",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 59,
                            IdEspecie = 2,
                            DescricaoRaca = "Pixie-bob",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 60,
                            IdEspecie = 2,
                            DescricaoRaca = "Raas",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 61,
                            IdEspecie = 2,
                            DescricaoRaca = "Ragamuffin",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 62,
                            IdEspecie = 2,
                            DescricaoRaca = "Ragdoll",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 63,
                            IdEspecie = 2,
                            DescricaoRaca = "Rex Alemão",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 64,
                            IdEspecie = 2,
                            DescricaoRaca = "Sagrado da Birmânia",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 65,
                            IdEspecie = 2,
                            DescricaoRaca = "Savannah",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 66,
                            IdEspecie = 2,
                            DescricaoRaca = "Scottish Fold",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 67,
                            IdEspecie = 2,
                            DescricaoRaca = "Selkirk Rex",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 68,
                            IdEspecie = 2,
                            DescricaoRaca = "Serengeti",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 69,
                            IdEspecie = 2,
                            DescricaoRaca = "Siamês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 70,
                            IdEspecie = 2,
                            DescricaoRaca = "Singapura",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 71,
                            IdEspecie = 2,
                            DescricaoRaca = "Snowshoe",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 72,
                            IdEspecie = 2,
                            DescricaoRaca = "Sokoke",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 73,
                            IdEspecie = 2,
                            DescricaoRaca = "Somali",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 74,
                            IdEspecie = 2,
                            DescricaoRaca = "Sphynx",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 75,
                            IdEspecie = 2,
                            DescricaoRaca = "Suphalak",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 76,
                            IdEspecie = 2,
                            DescricaoRaca = "Thai",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 77,
                            IdEspecie = 2,
                            DescricaoRaca = "Tiffany-Chantilly",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 78,
                            IdEspecie = 2,
                            DescricaoRaca = "Tonquinês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 79,
                            IdEspecie = 2,
                            DescricaoRaca = "Toyger",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 80,
                            IdEspecie = 2,
                            DescricaoRaca = "Van Turco",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 81,
                            IdEspecie = 2,
                            DescricaoRaca = "Wirehair Americano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 82,
                            IdEspecie = 2,
                            DescricaoRaca = "Manx de pelo longo",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 83,
                            IdEspecie = 2,
                            DescricaoRaca = "Asiático de Pelo Semi-Longo",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 84,
                            IdEspecie = 2,
                            DescricaoRaca = "Azul Russo",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 85,
                            IdEspecie = 2,
                            DescricaoRaca = "Balinês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 86,
                            IdEspecie = 2,
                            DescricaoRaca = "Bambino",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 87,
                            IdEspecie = 2,
                            DescricaoRaca = "Bicolor Oriental",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 88,
                            IdEspecie = 2,
                            DescricaoRaca = "Bobtail americano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 89,
                            IdEspecie = 2,
                            DescricaoRaca = "Bobtail japonês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 90,
                            IdEspecie = 2,
                            DescricaoRaca = "Bombaim",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 91,
                            IdEspecie = 2,
                            DescricaoRaca = "Burmês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 92,
                            IdEspecie = 2,
                            DescricaoRaca = "Burmila",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 93,
                            IdEspecie = 2,
                            DescricaoRaca = "California Spangled",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 94,
                            IdEspecie = 2,
                            DescricaoRaca = "Cingapura",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 95,
                            IdEspecie = 2,
                            DescricaoRaca = "Chartreux",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 96,
                            IdEspecie = 2,
                            DescricaoRaca = "Chausie",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 97,
                            IdEspecie = 2,
                            DescricaoRaca = "Colorpoint de pelo curto",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 98,
                            IdEspecie = 2,
                            DescricaoRaca = "Cornish Rex",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 99,
                            IdEspecie = 2,
                            DescricaoRaca = "Curl Americano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 100,
                            IdEspecie = 2,
                            DescricaoRaca = "Devon Rex",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 101,
                            IdEspecie = 2,
                            DescricaoRaca = "Donskoy",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 102,
                            IdEspecie = 2,
                            DescricaoRaca = "Dragon Li",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 103,
                            IdEspecie = 2,
                            DescricaoRaca = "Egeu",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 104,
                            IdEspecie = 2,
                            DescricaoRaca = "Gato-de-Bengala",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 105,
                            IdEspecie = 2,
                            DescricaoRaca = "Gato do Chipre",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 106,
                            IdEspecie = 2,
                            DescricaoRaca = "Exótico",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 107,
                            IdEspecie = 2,
                            DescricaoRaca = "Gato asiático",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 108,
                            IdEspecie = 2,
                            DescricaoRaca = "Gato Siberiano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 109,
                            IdEspecie = 2,
                            DescricaoRaca = "Havana marrom",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 110,
                            IdEspecie = 2,
                            DescricaoRaca = "Himalaio",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 111,
                            IdEspecie = 2,
                            DescricaoRaca = "Javanês",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 112,
                            IdEspecie = 2,
                            DescricaoRaca = "Korat",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 113,
                            IdEspecie = 2,
                            DescricaoRaca = "Khao Manee",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 114,
                            IdEspecie = 2,
                            DescricaoRaca = "Kurilian Bobtail",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 115,
                            IdEspecie = 2,
                            DescricaoRaca = "LaPerml",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 116,
                            IdEspecie = 2,
                            DescricaoRaca = "Levkoy ucraniano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 117,
                            IdEspecie = 2,
                            DescricaoRaca = "Lykoi",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 118,
                            IdEspecie = 2,
                            DescricaoRaca = "Maine Coon",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 119,
                            IdEspecie = 2,
                            DescricaoRaca = "Manx",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 120,
                            IdEspecie = 2,
                            DescricaoRaca = "Mau Árabe",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 121,
                            IdEspecie = 2,
                            DescricaoRaca = "Mau egípcio",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 122,
                            IdEspecie = 2,
                            DescricaoRaca = "Minskin",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 123,
                            IdEspecie = 2,
                            DescricaoRaca = "Mist Australiano",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 124,
                            IdEspecie = 2,
                            DescricaoRaca = "Munchkin",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 125,
                            IdEspecie = 2,
                            DescricaoRaca = "Nebelung",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 126,
                            IdEspecie = 2,
                            DescricaoRaca = "Norueguês da Floresta",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 127,
                            IdEspecie = 2,
                            DescricaoRaca = "Ocicat",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 128,
                            IdEspecie = 2,
                            DescricaoRaca = "Abissínio",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        },
                        new
                        {
                            IdRaca = 129,
                            IdEspecie = 2,
                            DescricaoRaca = "Angorá turco",
                            PorteRaca = "Médio",
                            crRaca = "-"
                        });
                });

            modelBuilder.Entity("carteiravacina.Models.Sexos", b =>
                {
                    b.Property<int>("IdSexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoSexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSexo");

                    b.ToTable("Sexos");

                    b.HasData(
                        new
                        {
                            IdSexo = 1,
                            DescricaoSexo = "Macho"
                        },
                        new
                        {
                            IdSexo = 2,
                            DescricaoSexo = "Femea"
                        });
                });

            modelBuilder.Entity("carteiravacina.Models.Situacao", b =>
                {
                    b.Property<int>("IdSituacao")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoSituacao")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdSituacao", "DescricaoSituacao");

                    b.ToTable("Situacao");

                    b.HasData(
                        new
                        {
                            IdSituacao = 1,
                            DescricaoSituacao = "Ativo"
                        },
                        new
                        {
                            IdSituacao = 2,
                            DescricaoSituacao = "Desaparecido"
                        },
                        new
                        {
                            IdSituacao = 3,
                            DescricaoSituacao = "Falecido"
                        },
                        new
                        {
                            IdSituacao = 4,
                            DescricaoSituacao = "Para adoção"
                        });
                });

            modelBuilder.Entity("carteiravacina.Models.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BairroTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplementoTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTutor")
                        .HasColumnType("int");

                    b.Property<int?>("PerfilIdCodigo")
                        .HasColumnType("int");

                    b.Property<int>("cpfTutor")
                        .HasColumnType("int");

                    b.Property<int>("crm")
                        .HasColumnType("int");

                    b.Property<string>("ufTutor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTutor");

                    b.HasIndex("PerfilIdCodigo");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("carteiravacina.Models.TutorAnimal", b =>
                {
                    b.Property<int>("IdTutor")
                        .HasColumnType("int");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTutor", "IdAnimal");

                    b.ToTable("TutorAnimal");
                });

            modelBuilder.Entity("carteiravacina.Models.Vacina", b =>
                {
                    b.Property<int>("IdVacina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriacaoVacina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<int>("doseVacina")
                        .HasColumnType("int");

                    b.Property<int>("intervaloVacina")
                        .HasColumnType("int");

                    b.HasKey("IdVacina");

                    b.ToTable("Vacina");

                    b.HasData(
                        new
                        {
                            IdVacina = 1,
                            DescriacaoVacina = "V8",
                            IdEspecie = 1,
                            doseVacina = 3,
                            intervaloVacina = 1
                        },
                        new
                        {
                            IdVacina = 2,
                            DescriacaoVacina = "V10",
                            IdEspecie = 1,
                            doseVacina = 3,
                            intervaloVacina = 1
                        },
                        new
                        {
                            IdVacina = 3,
                            DescriacaoVacina = "Gripe Canina",
                            IdEspecie = 1,
                            doseVacina = 2,
                            intervaloVacina = 1
                        },
                        new
                        {
                            IdVacina = 4,
                            DescriacaoVacina = "Giardíase",
                            IdEspecie = 1,
                            doseVacina = 2,
                            intervaloVacina = 1
                        },
                        new
                        {
                            IdVacina = 5,
                            DescriacaoVacina = "Anti-Rábica",
                            IdEspecie = 1,
                            doseVacina = 1,
                            intervaloVacina = 12
                        },
                        new
                        {
                            IdVacina = 6,
                            DescriacaoVacina = "Quádrupla Felina",
                            IdEspecie = 2,
                            doseVacina = 3,
                            intervaloVacina = 4
                        },
                        new
                        {
                            IdVacina = 7,
                            DescriacaoVacina = "Anti-Rábica",
                            IdEspecie = 2,
                            doseVacina = 1,
                            intervaloVacina = 12
                        });
                });

            modelBuilder.Entity("carteiravacina.Models.Animal", b =>
                {
                    b.HasOne("carteiravacina.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieIdEspecie");

                    b.HasOne("carteiravacina.Models.Sexos", "Sexos")
                        .WithMany()
                        .HasForeignKey("SexosIdSexo");

                    b.HasOne("carteiravacina.Models.Racas", "Racas")
                        .WithMany()
                        .HasForeignKey("RacasIdRaca", "RacasIdEspecie");

                    b.HasOne("carteiravacina.Models.Situacao", "Situacao")
                        .WithMany()
                        .HasForeignKey("SituacaoIdSituacao", "SituacaoDescricaoSituacao");

                    b.Navigation("Especie");

                    b.Navigation("Racas");

                    b.Navigation("Sexos");

                    b.Navigation("Situacao");
                });

            modelBuilder.Entity("carteiravacina.Models.CarteiraVacina", b =>
                {
                    b.HasOne("carteiravacina.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalIdAnimal");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("carteiravacina.Models.Tutor", b =>
                {
                    b.HasOne("carteiravacina.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilIdCodigo");

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
